name: Manual-exec

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    environment: Autopsd
    steps:

      - name: Checkout repo content
        uses: actions/checkout@v3 # checkout the repository content to github runner

      - name: Setup python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11.4' # install the python version needed
          
      - name: Execute psms-to-gsheet main-code # run main.py
        env:
          psdemail: ${{ secrets.PSDEMAIL }}
          psdpass: ${{ secrets.PSDPASS }}
          project_id: ${{ secrets.PROJECT_ID }}
          private_key_id: ${{ secrets.PRIVATE_KEY_ID }}
          private_key: ${{ secrets.PRIVATE_KEY }}
          client_email: ${{ secrets.CLIENT_EMAIL }}
          client_id: ${{ secrets.CLIENT_ID }}
          client_x509_cert_url: ${{ secrets.CLIENT_X509_CERT_URL }}
          sheetlink: ${{ secrets.SHEETLINK }}
        run: |
          source autopsd-venv/bin/activate
          python pypsd-gs.py
          if ${{ env.RETRY_PY == '1' }}; then pip install -r requirements.txt && python pypsd-gs.py; else echo "Initial Run Successful";fi
          
      - if: ${{ env.DSTORE_UPD == '1' && env.RETRY_PY != '1'}}
        name: Commit Datastore Update
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add datastore.crypt
          git add debug
          git diff-index --quiet HEAD || (git commit -a -m "Datastore Updated" --allow-empty)
      - if: ${{ env.RETRY_PY == '1' }}
        name: Commit Update Everything
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add -A
          git diff-index --quiet HEAD || (git commit -a -m "Python Runtime Update" --allow-empty)
      - if: ${{ env.DSTORE_UPD == '1' || env.RETRY_PY == '1' }}
        name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: main 
